# Generated by Django 4.2 on 2023-05-04 19:06

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('dept', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('reg_amount', models.IntegerField(null=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('total_fee', models.IntegerField(null=True)),
                ('paid', models.IntegerField(null=True)),
                ('remain', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('available', models.IntegerField(null=True)),
                ('issue', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to=account.models.user_image_file_path)),
                ('p_house_no', models.IntegerField()),
                ('p_socity', models.CharField(max_length=250)),
                ('p_landmark', models.CharField(max_length=250)),
                ('p_district', models.CharField(max_length=50)),
                ('p_state', models.CharField(max_length=50)),
                ('p_pincode', models.IntegerField()),
                ('t_house_no', models.IntegerField()),
                ('t_socity', models.CharField(max_length=250)),
                ('t_landmark', models.CharField(max_length=250)),
                ('t_district', models.CharField(max_length=50)),
                ('t_state', models.CharField(max_length=50)),
                ('t_pincode', models.IntegerField()),
                ('personal_no', models.IntegerField()),
                ('guardian_no', models.IntegerField()),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(default='male', max_length=255)),
                ('father_f_name', models.CharField(max_length=50)),
                ('father_l_name', models.CharField(max_length=50)),
                ('mother_f_name', models.CharField(max_length=50)),
                ('mother_l_name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('institute_roll', models.IntegerField()),
                ('university_roll', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
