# Generated by Django 4.2 on 2023-05-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('p_house_no', models.IntegerField()),
                ('p_socity', models.CharField(max_length=250)),
                ('p_landmark', models.CharField(max_length=250)),
                ('p_district', models.CharField(max_length=50)),
                ('p_state', models.CharField(max_length=50)),
                ('p_pincode', models.IntegerField()),
                ('t_house_no', models.IntegerField()),
                ('t_socity', models.CharField(max_length=250)),
                ('t_landmark', models.CharField(max_length=250)),
                ('t_district', models.CharField(max_length=50)),
                ('t_state', models.CharField(max_length=50)),
                ('t_pincode', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('faculty_id', models.IntegerField()),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
    ]
