# Generated by Django 4.2 on 2023-05-08 15:56

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_facultyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyinfo',
            name='image',
            field=models.ImageField(null=True, upload_to=account.models.user_image_file_path),
        ),
    ]
