# Generated by Django 4.2 on 2023-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_facultyinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('course', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('sub', models.CharField(max_length=200)),
            ],
        ),
    ]
