# Generated by Django 4.2 on 2023-05-09 19:25

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_facultyroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='studyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('sub', models.CharField(max_length=200)),
                ('unit', models.IntegerField()),
                ('file', models.FileField(null=True, upload_to=account.models.user_file_path)),
            ],
        ),
    ]
