# Generated by Django 4.2 on 2023-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='sub',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
