# Generated by Django 4.2 on 2023-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_attendancerecord_course_attendancerecord_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
    ]
